###############################################################################
# Created by write_sdc
###############################################################################
current_design ALU
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name __VIRTUAL_CLK__ -period 20.0000 
set_clock_uncertainty 0.2500 __VIRTUAL_CLK__
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {a[0]}]
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {a[1]}]
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {a[2]}]
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {a[3]}]
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {a[4]}]
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {a[5]}]
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {a[6]}]
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {a[7]}]
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {b[0]}]
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {b[1]}]
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {b[2]}]
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {b[3]}]
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {b[4]}]
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {b[5]}]
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {b[6]}]
set_input_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {b[7]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[0]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[10]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[11]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[12]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[13]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[14]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[15]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[16]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[17]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[18]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[19]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[1]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[2]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[3]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[4]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[5]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[6]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[7]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[8]}]
set_output_delay 0.2000 -clock [get_clocks {__VIRTUAL_CLK__}] -add_delay [get_ports {result[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {result[19]}]
set_load -pin_load 0.0334 [get_ports {result[18]}]
set_load -pin_load 0.0334 [get_ports {result[17]}]
set_load -pin_load 0.0334 [get_ports {result[16]}]
set_load -pin_load 0.0334 [get_ports {result[15]}]
set_load -pin_load 0.0334 [get_ports {result[14]}]
set_load -pin_load 0.0334 [get_ports {result[13]}]
set_load -pin_load 0.0334 [get_ports {result[12]}]
set_load -pin_load 0.0334 [get_ports {result[11]}]
set_load -pin_load 0.0334 [get_ports {result[10]}]
set_load -pin_load 0.0334 [get_ports {result[9]}]
set_load -pin_load 0.0334 [get_ports {result[8]}]
set_load -pin_load 0.0334 [get_ports {result[7]}]
set_load -pin_load 0.0334 [get_ports {result[6]}]
set_load -pin_load 0.0334 [get_ports {result[5]}]
set_load -pin_load 0.0334 [get_ports {result[4]}]
set_load -pin_load 0.0334 [get_ports {result[3]}]
set_load -pin_load 0.0334 [get_ports {result[2]}]
set_load -pin_load 0.0334 [get_ports {result[1]}]
set_load -pin_load 0.0334 [get_ports {result[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {b[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 1.500 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
